name: Androniki Pavlidou
favicon: null
layout_spectrum: 0.25361
typography_spectrum: 0.76247
title: 'Androniki Pavlidou Innovation and Tech Picks!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73184708-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202521'
    - '#b4abda'
    - '#911712'
    - '#ba5d78'
    - '#8e86af'
  brandStrength: 0.25
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
