name: Androniki Pavlidou
favicon: null
layout_spectrum: 0.74429
typography_spectrum: 0.76247
title: 'Androniki Pavlidou Innovation and Tech Picks!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73184708-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#a3a3a3'
    - '#5d5d5d'
    - '#bfea04'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
