name: Androniki Pavlidou
favicon: null
layout_spectrum: 0.26558
typography_spectrum: 0.76247
title: 'Androniki Pavlidou Innovation and Tech Picks!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73184708-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fe0000'
    - '#802f00'
    - '#fcfe00'
    - '#fe9e00'
  brandStrength: 0.25
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
