name: Androniki Pavlidou
favicon: null
layout_spectrum: 0.8635346298106015
typography_spectrum: 0.7516320797149092
title: 'Androniki Pavlidou Innovation and Tech Picks!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73184708-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020200'
    - '#f7e7cd'
    - '#7c7270'
    - '#39492e'
    - '#fb9d2c'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
